### PR TITLE
Installerscript for audiobookshelf

### PR DESCRIPTION
**Pull request by Sh4dowNight**
Installerscript for audiobookshelf

### CODE REVIEW

**Comment by brettpetch** [comment]
Happy with this other than the one change needed.

**Comment by Sh4dowNight** [comment]
> Happy with this other than the one change needed. Nice work. 

Thank you sir.

What change do you mean in particular?

Maybe it would be useful not to hardcode the version and implement a logic that always installs the latest version.

Besides that feel free to change whatever you desire.

**Comment by brettpetch** [comment]
```bash
echo 'This is unsupported software. You will not get help with this, please answer `yes` if you understand and wish to proceed'
if [[ -z ${eula} ]]; then
    read -r eula
fi

if ! [[ $eula =~ yes ]]; then
  echo "You did not accept the above. Exiting..."
  exit 1
else
  echo "Proceeding with installation"
fi
```

**Comment by Sh4dowNight** [comment]
Done!

**Comment by brettpetch** [comment]
Going to run this through shellcheck when I get home and ensure that everything is in order, then will squash and merge.

**Comment by redoXiD** [comment]
I already tested the script on my box, but somehow audiobookshelf does not start. When I run the executable directly, I get this error message:
image
Unfortunately, we were not able to reproduce the error yet (tested it on @Sh4dowNight's hbd boxes, hbd boxes of a few other users and a VPS), so further testing would be needed to identify the range of the problem. (it could be a different server configuration as I'm on a different server than the other boxes we tested.)
However, audiobookshelf versions up to 2.2.23 are working, the problem started with v2.3.0. 

I also found a bug report where the [same error](https://github.com/advplyr/audiobookshelf/issues/1939) occured on QNAP NAS devices. In an unpacked working qpkg file (v2.3.3) I discovered that the developer (of the QNAP installer) seems to have solved the problem copying a `node_sqlite3.node` file to the installation directory, but I was not able try the fix as as _this_ script runs the binary directly.

**Comment by brettpetch** [comment]
To me it sounds like sqlite isn't being compiled correctly, maybe a python issue?

**Pull request merged**
